[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cd_protocol"
version = "0.1.0"
description = "Binary protocol definitions for HeadUnit"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src/python"]
